# Generated by Django 3.2.7 on 2021-09-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_excelfileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='contact_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
